### ISSUE TITLE
Error in Exercise 2 task 3 step 10

### ISSUE THREAD

**Issue by daniakodeih** [Microsoft/MCW-Containers-and-DevOps#28] opened 2018-07-13 22:39 UTC
Deploying the web service cause this error 

Cluster 
Namespaces 
Nodes 
Persistent Volumes 
Roles 
Storage Classes 

Namespace
default

Overview 
Workloads 
Cron Jobs 
Daemon Sets 
Deployments 
Jobs 
Pods 
Replica Sets 
Replication Controllers 
Stateful Sets 
Discovery and Load Balancing 
Ingresses 
Services 
Config and Storage 
Config Maps 
Persistent Volume Claims 
Secrets 

Settings 
About 
Logs from 
web 

in 
web-6698dcf8fd-z9hdl 

format_color_text text_fields timer_off refresh 
  
exposure_zero file_download 

&gt; application-name@0.0.1 start /usr/src/app 
&gt; node server.js 

/usr/src/app/data-access/index.js:52 
var contentApiUrl = process.env.CONTENT_API_URL; 
    ^ 

SyntaxError: Identifier 'contentApiUrl' has already been declared 
    at new Script (vm.js:74:7) 
    at createScript (vm.js:246:10) 
    at Object.runInThisContext (vm.js:298:10) 
    at Module._compile (internal/modules/cjs/loader.js:657:28) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10) 
    at Module.load (internal/modules/cjs/loader.js:599:32) 
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12) 
    at Function.Module._load (internal/modules/cjs/loader.js:530:3) 
    at Module.require (internal/modules/cjs/loader.js:637:17) 
    at require (internal/modules/cjs/helpers.js:20:18) 
npm ERR! code ELIFECYCLE 
npm ERR! errno 1 
npm ERR! application-name@0.0.1 start: `node server.js` 
npm ERR! Exit status 1 
npm ERR!  
npm ERR! Failed at the application-name@0.0.1 start script. 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 

npm ERR! A complete log of this run can be found in: 
npm ERR!     /root/.npm/_logs/2018-07-13T22_37_06_583Z-debug.log

**Comment by jamesrcounts** [comment] 2018-07-15 02:09
Hello, this looks like a duplicate of #21, which is corrected in the latest master.

**Closed** 2018-07-19 23:08 UTC
